name: CI

on:name: CI
on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - name: build
        run: yarn build
        working-directory: ./functions
